spring.application.name=pawsandrequests
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=60
