package com.codecool.pawsandrequests.config;

import com.codecool.pawsandrequests.security.JwtAuthenticationFilter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpMethod;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;
import org.springframework.web.cors.CorsConfiguration;
import org.springframework.web.cors.CorsConfigurationSource;
import org.springframework.web.cors.UrlBasedCorsConfigurationSource;
// REVIEW(noob): @EnableMethodSecurity is switched on but no @PreAuthorize exists anywhere. Either use it (it would clean up the role switch in PostService.deletePost) or drop the annotation so the config does not promise something it does not do.

import java.util.List;

@Configuration
@EnableWebSecurity
@EnableMethodSecurity
public class SecurityConfig {

    private final JwtAuthenticationFilter jwtAuthenticationFilter;

    public SecurityConfig(
            final JwtAuthenticationFilter filter
    ) {
        this.jwtAuthenticationFilter = filter;
    }

    /**
     * Configures the {@link SecurityFilterChain} for the application.
     *
     * <p>This method is not {@code final} because Spring proxies
     * {@code @Configuration} classes with CGLIB to enforce singleton
     * semantics between {@code @Bean} methods, which requires bean
     * methods to stay non-final and overridable. A subclass overriding
     * this method should still register {@link JwtAuthenticationFilter}
     * before {@link UsernamePasswordAuthenticationFilter} to preserve
     * JWT authentication on the chain.
     *
     * @param http the {@link HttpSecurity} to configure
     * @return the built {@link SecurityFilterChain}
     * @throws Exception if the security configuration cannot be built
     * (NOTE: Javadoc is generated by claudecode)
     */
    @Bean
    // REVIEW(sec): disabling CSRF is correct for a stateless token API, but only because you send the JWT in the Authorization header. If you ever move the token into a cookie, this line becomes a real vulnerability.
    public SecurityFilterChain filterChain(
            final HttpSecurity http
    ) throws Exception {
// REVIEW(sec): this is the wrong way round, and it is the most important finding in the repo. The rule is deny by default: .anyRequest().authenticated() with an explicit permitAll for /api/auth/**. As written, every endpoint anyone adds from now on ships to production unprotected unless they remember to come back here and add a matcher. Right now only DELETE /posts/** is protected: GET /animals, which is supposed to be shelter-private, is wide open.

        http
            .cors(cors -> cors.configurationSource(corsConfigurationSource()))
            // REVIEW(sec): permitAll also covers /h2-console (see application.properties) and any future actuator endpoints.
            .csrf(csrf -> csrf.disable())
            .sessionManagement(session -> session
                // REVIEW(azure): frameOptions sameOrigin is only here to make the H2 console render. Once the console goes, drop this too.
                .sessionCreationPolicy(SessionCreationPolicy.STATELESS))
            .authorizeHttpRequests(auth -> auth
                    .requestMatchers(HttpMethod.POST, "/api/auth/login",
                            "/api/auth/registration").permitAll()
                    .requestMatchers(HttpMethod.GET, "/posts",
                            "/posts/**").permitAll()
                    .anyRequest().authenticated()
            )
            .headers(headers -> headers
                .frameOptions(frameOptions -> frameOptions.sameOrigin())
            )
            .addFilterBefore(
                    jwtAuthenticationFilter,
                    UsernamePasswordAuthenticationFilter.class
            );
        return http.build();
    }

    /**
     * Allows the frontend dev server (localhost:5173) to make cross
     * origin requests.
     * @return the CORS configuration source applied to all endpoints
     */
    @Bean
    public CorsConfigurationSource corsConfigurationSource() {
        CorsConfiguration configuration = new CorsConfiguration();
        configuration.setAllowedOrigins(List.of("http://localhost:5173"));
        configuration.setAllowedMethods(List.of(
                "GET", "POST", "PUT", "DELETE", "OPTIONS"));
        configuration.setAllowedHeaders(List.of("*"));
        UrlBasedCorsConfigurationSource source =
                new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", configuration);
        return source;
    }
}
