package com.codecool.pawsandrequests.config;

import com.codecool.pawsandrequests.security.JwtAuthenticationFilter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpMethod;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;
import org.springframework.web.cors.CorsConfiguration;
import org.springframework.web.cors.CorsConfigurationSource;
import org.springframework.web.cors.UrlBasedCorsConfigurationSource;

import java.util.List;

@Configuration
@EnableWebSecurity
@EnableMethodSecurity
public class SecurityConfig {

    private final JwtAuthenticationFilter jwtAuthenticationFilter;

    public SecurityConfig(
            final JwtAuthenticationFilter filter
    ) {
        this.jwtAuthenticationFilter = filter;
    }

    /**
     * Configures the {@link SecurityFilterChain} for the application.
     *
     * <p>This method is not {@code final} because Spring proxies
     * {@code @Configuration} classes with CGLIB to enforce singleton
     * semantics between {@code @Bean} methods, which requires bean
     * methods to stay non-final and overridable. A subclass overriding
     * this method should still register {@link JwtAuthenticationFilter}
     * before {@link UsernamePasswordAuthenticationFilter} to preserve
     * JWT authentication on the chain.
     *
     * @param http the {@link HttpSecurity} to configure
     * @return the built {@link SecurityFilterChain}
     * @throws Exception if the security configuration cannot be built
     * (NOTE: Javadoc is generated by claudecode)
     */
    @Bean
    public SecurityFilterChain filterChain(
            final HttpSecurity http
    ) throws Exception {

        http
            .cors(cors -> cors.configurationSource(corsConfigurationSource()))
            .csrf(csrf -> csrf.disable())
            .sessionManagement(session -> session
                .sessionCreationPolicy(SessionCreationPolicy.STATELESS))
            .authorizeHttpRequests(auth -> auth
                    .requestMatchers(HttpMethod.POST, "/api/auth/login",
                            "/api/auth/registration").permitAll()
                    .requestMatchers(HttpMethod.GET, "/posts",
                            "/posts/**").permitAll()
                    .requestMatchers(HttpMethod.GET, "/shelters",
                            "/shelters/**").permitAll()
                    .anyRequest().authenticated()
            )
            .headers(headers -> headers
                .frameOptions(frameOptions -> frameOptions.sameOrigin())
            )
            .addFilterBefore(
                    jwtAuthenticationFilter,
                    UsernamePasswordAuthenticationFilter.class
            );
        return http.build();
    }

    /**
     * Allows the frontend dev server (localhost:5173) to make cross
     * origin requests.
     * @return the CORS configuration source applied to all endpoints
     */
    @Bean
    public CorsConfigurationSource corsConfigurationSource() {
        CorsConfiguration configuration = new CorsConfiguration();
        configuration.setAllowedOrigins(List.of("http://localhost:5173"));
        configuration.setAllowedMethods(List.of(
                "GET", "POST", "PUT", "DELETE", "OPTIONS"));
        configuration.setAllowedHeaders(List.of("*"));
        UrlBasedCorsConfigurationSource source =
                new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", configuration);
        return source;
    }
}
