package com.codecool.pawsandrequests.config;

import com.codecool.pawsandrequests.security.JwtAuthenticationFilter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

@Configuration
@EnableWebSecurity
@EnableMethodSecurity
public class SecurityConfig {

    private final JwtAuthenticationFilter jwtAuthenticationFilter;

    public SecurityConfig(
            final JwtAuthenticationFilter filter
    ) {
        this.jwtAuthenticationFilter = filter;
    }

    /**
     * Configures the {@link SecurityFilterChain} for the application.
     *
     * <p>This method is not {@code final} because Spring proxies
     * {@code @Configuration} classes with CGLIB to enforce singleton
     * semantics between {@code @Bean} methods, which requires bean
     * methods to stay non-final and overridable. A subclass overriding
     * this method should still register {@link JwtAuthenticationFilter}
     * before {@link UsernamePasswordAuthenticationFilter} to preserve
     * JWT authentication on the chain.
     *
     * @param http the {@link HttpSecurity} to configure
     * @return the built {@link SecurityFilterChain}
     * @throws Exception if the security configuration cannot be built
     * (NOTE: Javadoc is generated by claudecode)
     */
    @Bean
    public SecurityFilterChain filterChain(
            final HttpSecurity http
    ) throws Exception {

        http
            .csrf(csrf -> csrf.disable())
            .sessionManagement(session -> session
                .sessionCreationPolicy(SessionCreationPolicy.STATELESS))
            .authorizeHttpRequests(auth -> auth
                .anyRequest().permitAll()
            )
            .headers(headers -> headers
                .frameOptions(frameOptions -> frameOptions.sameOrigin())
            )
            .addFilterBefore(
                    jwtAuthenticationFilter,
                    UsernamePasswordAuthenticationFilter.class
            );
        return http.build();
    }
}
