package com.codecool.paws_and_requests.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

@Configuration
public class PasswordConfig {
    /**
     * Provides the {@link PasswordEncoder} used to hash and verify
     * user passwords.
     *
     * <p>This method is not {@code final} because Spring proxies
     * {@code @Configuration} classes with CGLIB to enforce singleton
     * semantics between {@code @Bean} methods, which requires bean
     * methods to stay non-final and overridable.
     *
     * @return a {@link BCryptPasswordEncoder} instance
     * (NOTE: Javadoc is generated by claudecode)
     */
    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }
}
