-- Schema for Paws and Requests.
--
-- This mirrors the schema of the Azure database exactly, so a fresh local
-- database is structurally identical to production. Flyway owns the schema:
-- spring.jpa.hibernate.ddl-auto stays on "validate" and never creates tables.

CREATE TABLE picture (
    id bigint NOT NULL,
    content_type character varying(255) NOT NULL,
    data bytea NOT NULL,
    CONSTRAINT picture_pkey PRIMARY KEY (id)
);

ALTER TABLE picture ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE users (
    picture_id bigint,
    id uuid NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    org_nr character varying(255),
    password character varying(255) NOT NULL,
    phone_number character varying(255),
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (
        role::text = ANY (ARRAY['ADMIN'::character varying, 'USER'::character varying,
            'SHELTERUSER'::character varying]::text[])),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_picture_id_key UNIQUE (picture_id)
);

CREATE TABLE shelter (
    picture_id bigint,
    address character varying(255),
    description character varying(255),
    org_nr character varying(255) NOT NULL,
    shelter_name character varying(255) NOT NULL,
    CONSTRAINT shelter_pkey PRIMARY KEY (org_nr),
    CONSTRAINT shelter_picture_id_key UNIQUE (picture_id)
);

CREATE TABLE animal (
    age integer NOT NULL,
    id uuid NOT NULL,
    gender character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    org_nr character varying(255) NOT NULL,
    species character varying(255) NOT NULL,
    CONSTRAINT animal_gender_check CHECK (
        gender::text = ANY (ARRAY['MALE'::character varying,
            'FEMALE'::character varying]::text[])),
    CONSTRAINT animal_species_check CHECK (
        species::text = ANY (ARRAY['DOG'::character varying,
            'CAT'::character varying]::text[])),
    CONSTRAINT animal_pkey PRIMARY KEY (id)
);

CREATE TABLE post (
    animal_id uuid NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    description character varying(1000) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT post_pkey PRIMARY KEY (id)
);

CREATE TABLE post_picture (
    picture_id bigint NOT NULL,
    post_id uuid NOT NULL,
    CONSTRAINT post_picture_picture_id_key UNIQUE (picture_id)
);

CREATE TABLE adoption_form (
    id uuid NOT NULL,
    post_id uuid NOT NULL,
    user_id uuid NOT NULL,
    content character varying(255) NOT NULL,
    CONSTRAINT adoption_form_pkey PRIMARY KEY (id)
);

-- Foreign keys -----------------------------------------------------------------
-- Named by hand. Hibernate's generated names are opaque hashes like
-- fk55rcy2y2s5eg82plj7lby8c9n, which are unreadable in error messages and in
-- pg_constraint queries. Nothing depends on these names: validate only checks
-- tables and columns, and Postgres tracks constraints internally by OID.
ALTER TABLE ONLY users
    ADD CONSTRAINT fk_users_picture
    FOREIGN KEY (picture_id) REFERENCES picture(id);

ALTER TABLE ONLY users
    ADD CONSTRAINT fk_users_shelter
    FOREIGN KEY (org_nr) REFERENCES shelter(org_nr);

ALTER TABLE ONLY shelter
    ADD CONSTRAINT fk_shelter_picture
    FOREIGN KEY (picture_id) REFERENCES picture(id);

ALTER TABLE ONLY animal
    ADD CONSTRAINT fk_animal_shelter
    FOREIGN KEY (org_nr) REFERENCES shelter(org_nr);

ALTER TABLE ONLY post
    ADD CONSTRAINT fk_post_animal
    FOREIGN KEY (animal_id) REFERENCES animal(id);

ALTER TABLE ONLY post
    ADD CONSTRAINT fk_post_user
    FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY post_picture
    ADD CONSTRAINT fk_post_picture_post
    FOREIGN KEY (post_id) REFERENCES post(id);

ALTER TABLE ONLY post_picture
    ADD CONSTRAINT fk_post_picture_picture
    FOREIGN KEY (picture_id) REFERENCES picture(id);

ALTER TABLE ONLY adoption_form
    ADD CONSTRAINT fk_adoption_form_user
    FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY adoption_form
    ADD CONSTRAINT fk_adoption_form_post
    FOREIGN KEY (post_id) REFERENCES post(id);
